#!/usr/bin/env python3
"""Generate the QPACK static table for Sources/PeregrineHTTP/QPACKTables.swift.

RFC 9204 appendix A lists 99 entries. Rather than transcribe them -- where one
wrong character would show up much later as a header that decodes to the wrong
thing -- each slot is read back out of an independent implementation: a block
containing nothing but "indexed field line, static table, index i" is handed to
pylsqpack, which answers with the name and value that index means.

Run inside a virtualenv that has pylsqpack (aioquic pulls it in):

    python scripts/gen-qpack-table.py > Sources/PeregrineHTTP/QPACKTables.swift
"""
import sys

import pylsqpack


def prefixed(value, prefix_bits, pattern):
    """RFC 7541 section 5.1 integer encoding, which QPACK reuses."""
    limit = (1 << prefix_bits) - 1
    if value < limit:
        return bytes([pattern | value])
    out = bytearray([pattern | limit])
    value -= limit
    while value >= 128:
        out.append((value % 128) + 128)
        value //= 128
    out.append(value)
    return bytes(out)


def entry(index):
    decoder = pylsqpack.Decoder(0, 0)
    # Field section prefix: required insert count 0, delta base 0.
    block = b"\x00\x00" + prefixed(index, 6, 0xC0)
    _, headers = decoder.feed_header(index * 4, block)
    return headers[0]


def swift_literal(b):
    out = '"'
    for ch in b:
        c = chr(ch)
        if c == '"' or c == "\\":
            out += "\\" + c
        elif 32 <= ch < 127:
            out += c
        else:
            out += "\\u{%02x}" % ch
    return out + '"'


def main():
    entries = []
    for i in range(99):
        try:
            name, value = entry(i)
        except Exception as exc:                        # pragma: no cover
            print("index %d failed: %s" % (i, exc), file=sys.stderr)
            return 1
        entries.append((name, value))

    print("//===----------------------------------------------------------------------===//")
    print("// The QPACK static table (RFC 9204 appendix A).")
    print("//")
    print("// Generated by scripts/gen-qpack-table.py, which reads each slot back out of")
    print("// an independent QPACK implementation rather than transcribing the RFC: a")
    print("// single wrong character here would surface much later as a header that")
    print("// decodes to something plausible and wrong.")
    print("//")
    print("// Unlike HPACK's, this table is indexed from zero, and many entries share a")
    print("// name with different values -- which is why the name lookup below returns the")
    print("// first slot for a name and the caller decides whether the value matches.")
    print("//===----------------------------------------------------------------------===//")
    print()
    print("public enum QPACKTables {")
    print("    /// name, value")
    print("    public static let staticTable: [(String, String)] = [")
    for name, value in entries:
        print("        (%s, %s)," % (swift_literal(name), swift_literal(value)))
    print("    ]")
    print("}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
